In [1]:
import pandas as pd
import numpy as np
import gensim.models
import seaborn as sb
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!pip install tensorflow==1.13.1
! pip install tensorflow-hub==0.7.0


     |████████████████████████████████| 92.6MB 62kB/s 
     |████████████████████████████████| 3.2MB 37.1MB/s 
     |████████████████████████████████| 368kB 35.2MB/s 
     |████████████████████████████████| 51kB 4.0MB/s 
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1
     |████████████████████████████████| 92kB 3.4MB/s 
  Found existing installation: tensorflow-hub 0.11.0
    Uninstalling tensorflow-hub-0.11.0:
      Successfully uninstalled tensorflow-hub-0.11.0


In [4]:
import tensorflow_hub as hub
import tensorflow as tf
class UseSentenceEmbedding():
    def __init__(self):
        # g = tf.Graph()
        with tf.device('/GPU:0'):
        # We will be feeding 1D tensors of text into the graph.
            self.text_input = tf.placeholder(dtype=tf.string, shape=[None])
            
            #kindly replace the location in hub.module with the url commented out below

            # "https://tfhub.dev/google/universal-sentence-encoder-large/3"
            embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder-large/3")
            self.embedded_text = embed(self.text_input)
            init_op = tf.group([tf.global_variables_initializer(), tf.tables_initializer()])
        # g.finalize()

        self.session = tf.Session(config=tf.ConfigProto( allow_soft_placement=True))
        self.session.run(init_op)
        print("init _____")



    def get_tokenized_sents_embeddings_USE(self, sents,expand=False):

           
        vectors_USE =  self.session.run(self.embedded_text, feed_dict={self.text_input: sents})

        return vectors_USE

use_embedding = UseSentenceEmbedding()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

Instructions for updating:
Colocations handled automatically by placer.


Instructions for updating:
Colocations handled automatically by placer.


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


init _____


In [5]:
!cp "/content/drive/MyDrive/Information_retrieval_project/QC_science/train_QC_data.csv" /content
!cp "/content/drive/MyDrive/Information_retrieval_project/QC_science/test_QC_data.csv" /content
!cp "/content/drive/MyDrive/Information_retrieval_project/QC_science/val_QC_data.csv" /content


In [6]:
import pandas as pd
train_data = pd.read_csv("train_QC_data.csv")
test_data = pd.read_csv("test_QC_data.csv")
val_data = pd.read_csv("val_QC_data.csv")
train_data
from google.colab import files

In [7]:
import re
def clean_sentence(question):
  # print(question)
  question = re.sub('<[^>]*>', ' ',question)
  question = re.sub(' +', ' ', question)
  question = re.sub('\xa0','',question)
  question = question.rstrip()
  question = re.sub('nan','',question)
  question = re.sub(u'\u2004','',question)
  question = re.sub(u'\u2009','',question)

  # question = question.decode("utf-8")
  # question = question.replace(u'\u200\d*','').encode("utf-8")
  question = re.sub('&nbsp','',question)
  question = re.sub('&ndash','',question)
  question = re.sub('\r','',question)
  question = re.sub('\t','',question)
  question = re.sub('\n',' ',question)

  question = re.sub('MathType@.*','',question)
  question = re.sub('&thinsp','',question)
  question = re.sub('&times','',question)
  question = re.sub('\u200b','',question)
  question = re.sub('&rarr;;;','',question)

  return question

In [8]:

from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()
LE.fit_transform(pd.concat([train_data['QCLabel'],test_data['QCLabel']]))
train_data['label'] = LE.transform(train_data['QCLabel'])
train_data.head()

questionID originalQuestionID  ...       fold label
0        VASoL_2008_3_34                 34  ...       Easy   399
1          MCAS_2015_8_6                  6  ...       Easy   260
2      Mercury_SC_417677             417677  ...  Challenge   293
3        Mercury_7230423            7230423  ...       Easy   103
4  NYSEDREGENTS_2007_8_6                  6  ...  Challenge   171

[5 rows x 15 columns]

In [9]:
def get_labels(prediction):
    predicted_label =  LE.inverse_transform([prediction])
    return predicted_label[0]

In [10]:
# LE_test = LabelEncoder()

test_data['label'] = LE.transform(test_data['QCLabel'])
test_data.head()

questionID originalQuestionID  ...       fold label
0     Mercury_409529             409529  ...  Challenge   416
1    Mercury_7090790            7090790  ...  Challenge   336
2   TIMSS_2007_8_pg7                pg7  ...  Challenge   354
3    Mercury_7014455            7014455  ...       Easy   292
4  NAEP_2000_8_S21+4              S21+4  ...  Challenge   324

[5 rows x 15 columns]

In [11]:
val_data['label'] = LE.transform(val_data['QCLabel'])
val_data.head()

questionID originalQuestionID  ...       fold label
0  MCAS_2006_9_30-v1                 30  ...  Challenge   329
1  Mercury_SC_401144             401144  ...       Easy    43
2   NCEOGA_2013_8_46                 46  ...       Easy     2
3     Mercury_417146             417146  ...  Challenge   222
4    Mercury_7283833            7283833  ...  Challenge   108

[5 rows x 15 columns]

In [12]:
train_features, test_features, train_labels, test_labels = train_data["Question"].values,test_data["Question"].values,train_data["label"].values,test_data["label"].values
val_features,val_labels = val_data["Question"].values, val_data["label"].values

In [13]:
train_features = use_embedding.get_tokenized_sents_embeddings_USE(train_features)
test_features = use_embedding.get_tokenized_sents_embeddings_USE(test_features)
print(train_features.shape,test_features.shape)

(5597, 512) (1400, 512)


In [14]:
#parameters = {'solver':['newton-cg', 'lbfgs','sag', 'saga'], 'C':[0.01,0.1,1, 10]}
log = LogisticRegression(max_iter=1000)
#clf = GridSearchCV(log, parameters)
log.fit(train_features, train_labels)
#clf.best_params_

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
import joblib
joblib.dump(train_features,'train_features_log_QC_science')

['train_features_log_QC_science']

In [16]:
joblib.dump(test_features,'test_features_log_QC_science')

['test_features_log_QC_science']

In [17]:
!mv train_features_log_QC_science "/content/drive/MyDrive/Information_retrieval_project/"
!mv test_features_log_QC_science "/content/drive/MyDrive/Information_retrieval_project/"

In [15]:
y_predict = log.predict_proba(test_features)
print(y_predict.shape)

(1400, 416)


In [40]:
final_predictions =[]
flat_predictions = y_predict
for prediction in flat_predictions:
  final_predictions.append(np.argsort(prediction.reshape(1,-1), axis=1)[:,-20:].squeeze())

In [27]:
import tensorflow as tf
y_true = np.array(test_labels)
y_true = tf.identity(y_true)
y_pred = np.array(final_predictions)
y_pred = tf.identity(y_pred)
print(y_pred.shape,y_true.shape)
k = 8
recall, update_recall = tf.compat.v1.metrics.recall_at_top_k(y_true, y_pred, 5)
precision, update_precision = tf.compat.v1.metrics.precision_at_top_k(y_true, y_pred, 5)

tmp_rank = tf.nn.top_k(y_pred, 5)
stream_vars = [i for i in tf.local_variables()]

with tf.Session(config=tf.ConfigProto( allow_soft_placement=True)) as sess:
    sess.run(tf.local_variables_initializer())
    # print("precision",sess.run(update_precision))
    # print("precision",sess.run(precision))

    print("update_recall: ",sess.run(update_recall ))
    print("recall",sess.run(recall))

    print("STREAM_VARS: ",(sess.run(stream_vars)))
    print("TMP_RANK: ",sess.run(y_pred))

(1400, 5) (1400,)
update_recall:  0.21571428571428572
recall 0.21571428571428572
STREAM_VARS:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 302.0, 1098.0, 0.0, 0.0]
TMP_RANK:  [[229 142 410 412 413]
 [ 78  54  85  52  46]
 [327 295 326 351 325]
 ...
 [224 225 101 223 229]
 [220 138 158 142 141]
 [220  31  33 101  10]]


In [29]:
import tensorflow as tf
y_true = np.array(test_labels)
y_true = tf.identity(y_true)
y_pred = np.array(final_predictions)
y_pred = tf.identity(y_pred)
print(y_pred.shape,y_true.shape)
k = 8
recall, update_recall = tf.compat.v1.metrics.recall_at_top_k(y_true, y_pred, 10)
precision, update_precision = tf.compat.v1.metrics.precision_at_top_k(y_true, y_pred, 10)

tmp_rank = tf.nn.top_k(y_pred, 10)
stream_vars = [i for i in tf.local_variables()]

with tf.Session(config=tf.ConfigProto( allow_soft_placement=True)) as sess:
    sess.run(tf.local_variables_initializer())
    # print("precision",sess.run(update_precision))
    # print("precision",sess.run(precision))

    print("update_recall: ",sess.run(update_recall ))
    print("recall",sess.run(recall))

    print("STREAM_VARS: ",(sess.run(stream_vars)))
    print("TMP_RANK: ",sess.run(y_pred))

(1400, 10) (1400,)
update_recall:  0.2935714285714286
recall 0.2935714285714286
STREAM_VARS:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 411.0, 989.0, 0.0, 0.0]
TMP_RANK:  [[223 220 414 ... 410 412 413]
 [332  62  33 ...  85  52  46]
 [339 334 335 ... 326 351 325]
 ...
 [216 227 185 ... 101 223 229]
 [162  80 196 ... 158 142 141]
 [ 12 265  22 ...  33 101  10]]


In [39]:
import tensorflow as tf
y_true = np.array(test_labels)
y_true = tf.identity(y_true)
y_pred = np.array(final_predictions)
y_pred = tf.identity(y_pred)
print(y_pred.shape,y_true.shape)
k = 8
recall, update_recall = tf.compat.v1.metrics.recall_at_top_k(y_true, y_pred, 15)
precision, update_precision = tf.compat.v1.metrics.precision_at_top_k(y_true, y_pred, 15)

tmp_rank = tf.nn.top_k(y_pred, 15)
stream_vars = [i for i in tf.local_variables()]

with tf.Session(config=tf.ConfigProto( allow_soft_placement=True)) as sess:
    sess.run(tf.local_variables_initializer())
    # print("precision",sess.run(update_precision))
    # print("precision",sess.run(precision))

    print("update_recall: ",sess.run(update_recall ))
    print("recall",sess.run(recall))

    print("STREAM_VARS: ",(sess.run(stream_vars)))
    print("TMP_RANK: ",sess.run(y_pred))

(1400, 15) (1400,)
update_recall:  0.35
recall 0.35
STREAM_VARS:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 490.0, 910.0, 0.0, 0.0]
TMP_RANK:  [[ 86 225 118 ... 410 412 413]
 [ 60  61  47 ...  85  52  46]
 [316 338 354 ... 326 351 325]
 ...
 [237 125 398 ... 101 223 229]
 [165 119 205 ... 158 142 141]
 [ 26 236  62 ...  33 101  10]]


In [41]:
import tensorflow as tf
y_true = np.array(test_labels)
y_true = tf.identity(y_true)
y_pred = np.array(final_predictions)
y_pred = tf.identity(y_pred)
print(y_pred.shape,y_true.shape)
k = 8
recall, update_recall = tf.compat.v1.metrics.recall_at_top_k(y_true, y_pred, 20)
precision, update_precision = tf.compat.v1.metrics.precision_at_top_k(y_true, y_pred, 20)

tmp_rank = tf.nn.top_k(y_pred, 20)
stream_vars = [i for i in tf.local_variables()]

with tf.Session(config=tf.ConfigProto( allow_soft_placement=True)) as sess:
    sess.run(tf.local_variables_initializer())
    # print("precision",sess.run(update_precision))
    # print("precision",sess.run(precision))

    print("update_recall: ",sess.run(update_recall ))
    print("recall",sess.run(recall))

    print("STREAM_VARS: ",(sess.run(stream_vars)))
    print("TMP_RANK: ",sess.run(y_pred))

(1400, 20) (1400,)
update_recall:  0.39285714285714285
recall 0.39285714285714285
STREAM_VARS:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 550.0, 850.0, 0.0, 0.0]
TMP_RANK:  [[234  10 143 ... 410 412 413]
 [165 334 196 ...  85  52  46]
 [331 398 312 ... 326 351 325]
 ...
 [413 168 158 ... 101 223 229]
 [112  74 118 ... 158 142 141]
 [263 413 252 ...  33 101  10]]
